spring.application.name=scoutly

spring.datasource.url=jdbc:postgresql://localhost:5432/scoutly
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:senha}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=scoutly_user
spring.rabbitmq.password=scoutly_pass